server:
  port: 8090
  servlet:
    context-path: /basic
spring:
  application:
    name: basic-authorization-api
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./user;MODE=PostgreSQL
    username: sa
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      settings:
        web-allow-others: false

jwt:
  access:
    secret: 977kgj53ft845tl98v6htfd52t9l38645jd394r36d33d
    lifetime: 1m
  refresh:
    secret: 028x3jre274hs27er946rt2th5x6m77cgtercgerg72jrd
    lifetime: 10m
